spring.application.name=RpgBackend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/rpg
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# API externes
app.dnd-api.base-url=https://www.dnd5eapi.co/api
app.openweather.base-url=https://api.openweathermap.org/data/2.5
app.openweather.api-key=26e3161e6d11ad40aa1cf16abfc1a213
app.youtube.api-key=AIzaSyCkE86EOAjPJiDgLO4yw4q326VgSqiWU2Q
