spring.application.name=RpgBackend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/rpg
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# API externes
app.dnd-api.base-url=https://www.dnd5eapi.co/api
